/*
 * This file defines the data structures and constants required to represent and process system call traces 
 * generated by the recorder. Each system call trace entry includes a sequence number, the system call identifier, 
 * its arguments, the return value, the associated error code (if any), and any data written to user space. The recorder 
 * serializes these system call traces to a trace file, which is subsequently consumed by the mutator. The mutator may 
 * inspect or modify individual trace entries and forwards them over pipes to the replayer. The replayer then deserializes 
 * the received traces to reconstruct the original system call information for replay.
 
*/

#ifndef TRACE_DEFS_H
#define TRACE_DEFS_H

#include <stdint.h>

typedef enum 
{
	SYS_TYPE_SOCKET,
	SYS_TYPE_FCNTL,
	SYS_TYPE_BIND,
	SYS_TYPE_LISTEN,
	SYS_TYPE_SETSOCKOPT,
	SYS_TYPE_ACCEPT,
	SYS_TYPE_NANOSLEEP,
	SYS_TYPE_RECV
} syscall_type_t;

/* The Common Header: Every system call trace has this */
typedef struct {
    uint64_t seq_num;		//For single-threaded this works. For multi-threaded, add timestamp
    syscall_type_t type;
    int64_t ret_val;
    int32_t saved_errno;
    uint32_t body_len;
} record_header_t;

/* Data for socket system call */
typedef struct {
    int domain;
    int type;
    int protocol;
} socket_data_t;

/* Data for fcntl system call */
typedef struct {
    int fd;        // file descriptor
    int cmd;       // fcntl command
    int64_t arg;   // optional argument, 0 if unused
} fcntl_data_t;

/* Data for setsockopt system call */
typedef struct {
    int sockfd;
    int level;
    int optname;
    uint32_t optlen;
    uint8_t optval[64]; 
} setsockopt_data_t;

/* Data for bind system call */
typedef struct {
    int sockfd;
    uint32_t addrlen;
    uint8_t addr[128];  // length enough to hold sockaddr_in, sockaddr_in6, sockaddr_un
} bind_data_t;

/* Data for listen system call */
typedef struct {
    int sockfd;
    int backlog;
} listen_data_t;

/* Data for accept system call */
typedef struct {
    int sockfd;            // listening socket
    int newfd;             // returned accepted socket
    socklen_t addrlen;      // length of addr which is returned after accept() is invoked
    uint8_t addr[128];     // address of peer socket (sockaddr_in, sockaddr_in6, sockaddr_un)
} accept_data_t;

/* Data for nanosleep system call */
typedef struct {
    uint64_t usec;           // usleep argument
    struct timespec rem;     // optional remaining time if syscall was interrupted
    int rem_valid;           // 1 if rem pointer was non-NULL and copied
} nanosleep_data_t;

/* Data for recvfrom system call */
typedef struct {
    int sockfd;
    uint8_t buf[4096];    // actual received data, size = ret_val
    uint32_t len;         // requested buffer length
    int flags;    
    uint32_t addrlen;     // if src_addr is not NULL
    uint8_t src_addr[128];// peer address

} recv_data_t;

/* replayer → mutator */
typedef struct {
    uint64_t seq_num;
    syscall_type_t syscall_type;   // syscall_type_t
} replay_req_t;

/* mutator → replayer */
typedef struct {
    uint32_t match;          // 1 = matched, 0 = ignore
} replay_resp_t;

#endif
